import 'package:flutter/material.dart';
import '../utils/theme_utils.dart';
import '../widgets/glass_header.dart';
import 'package:provider/provider.dart';
import '../providers/theme_provider.dart';

class LegalScreen extends StatelessWidget {
  const LegalScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Provider.of<ThemeProvider>(context).isDarkMode;
    return Scaffold(
      backgroundColor: FuturisticTheme.getBackgroundColor(isDark),
      body: SafeArea(
        child: Column(
          children: [
            const GlassHeader(title: 'Legal Documents'),
            Expanded(
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  _buildSection("Privacy Policy", _privacyPolicy, context),
                  const SizedBox(height: 20),
                  _buildSection("Terms of Service", _termsOfService, context),
                  const SizedBox(height: 20),
                  Center(
                    child: Text(
                      "Last Updated: Dec 2025",
                      style: TextStyle(
                          color: FuturisticTheme.textGray, fontSize: 12),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSection(String title, String content, BuildContext context) {
    final isDark = Provider.of<ThemeProvider>(context).isDarkMode;
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      child: ExpansionTile(
        collapsedBackgroundColor:
            FuturisticTheme.getSurfaceColor(isDark).withOpacity(0.5),
        backgroundColor:
            FuturisticTheme.getSurfaceColor(isDark).withOpacity(0.8),
        iconColor: FuturisticTheme.getAccentColor(isDark),
        collapsedIconColor: FuturisticTheme.getAccentColor(isDark),
        title: Text(
          title,
          style: FuturisticTheme.getHeaderStyle(isDark).copyWith(fontSize: 16),
        ),
        children: [
          Container(
            padding: const EdgeInsets.all(16),
            color: Colors.black12,
            child: Text(content,
                style: FuturisticTheme.getBodyStyle(isDark)
                    .copyWith(fontSize: 14)),
          ),
        ],
      ),
    );
  }

  static const String _privacyPolicy = """
1. Data Collection: We do not collect personal data on our servers. All AI processing can be done locally or via your own API keys.
2. Local Storage: Chat history and settings are stored locally on your device.
3. Third-Party Services: If you stick to Cloud Mode, data is sent to the respective provider (OpenAI, Groq, etc.) according to their policies.
""";

  static const String _termsOfService = """
1. Usage: You agree to use this app responsibly.
2. Liability: The developers are not liable for any content generated by the AI.
3. Age Requirement: Users must be 13+.
""";
}
